name: Windows CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x' 
      - uses: BSFishy/pip-action@v1
        with:
          packages: conan
    
      - name: Pip Install
        run: python -m install conan
        
      - name: Conan Install
        run: conan install . -s compiler.libcxx=libstdc++11 --build missing
